arttor/helmify

examples/operator/templates/mutating-webhook-configuration.yaml, go.mod, pkg/app/app.go, pkg/processor/deployment/deployment.go, pkg/processor/webhook/mutating.go, pkg/processor/webhook/mutating_test.go, pkg/processor/webhook/validating.go, pkg/processor/webhook/validating_test.go, pkg/processor/webhook/webhook.go, test_data/k8s-operator-kustomize.output
1. Preserve the line break before `annotation`.
2. Trim the prefix of cert-name properly.
3. Add support for MutatingWebhookConfiguration.
=> Fix pod annotation, cert-name and add support for MutatingWebhookConfiguration

examples/operator/templates/manifestcephvolume-crd.yaml, examples/operator/templates/serving-cert.yaml, pkg/helmify/model.go, pkg/metadata/metadata.go, pkg/processor/crd/crd.go, pkg/processor/webhook/cert.go, test_data/k8s-operator-kustomize.output
1. Add support to use template for conversion webhook in CRD.
2. Template dnsNames because they are assembled by kustomize.
=> Update namespace in conversion webhook in CRD and template dnsName values.

pkg/processor/configmap/configmap.go
I have a use case where I'd like to allow a complete key in a configMap.key to be
templated. This seems to accomplist it, wdyt?
=> feat(configmap): template when len(map[]) == 0

examples/app/templates/deployment.yaml, examples/app/values.yaml, examples/operator/templates/deployment.yaml, examples/operator/templates/serving-cert.yaml, examples/operator/values.yaml, pkg/cluster/domain.go, pkg/helm/chart.go, pkg/processor/deployment/deployment.go, pkg/processor/webhook/cert.go
Some kubernetes clusters have cluster domain not being `cluster.local`. Make the generated chart to be able to customize this value.
=> Support custom cluster domain

examples/operator/templates/cephvolume-crd.yaml, examples/operator/templates/manifestcephvolume-crd.yaml, pkg/processor/crd/crd.go, pkg/processor/crd/crd_test.go, test_data/k8s-operator-kustomize.output
This change adds any labels present on the source CRD to the generated CRD template. This is useful for preserving any labels which were generated before calling helmify, eg during the kustomize phase.
Also removed hardcoded instances of `controller-gen.kubebuilder.io/version: v0.7.0` from the annotations section.
Also renamed `versions` variable to `specYaml` for clarity.
=> Apply Source CRD labels to CRDs Templates

.github/workflows/ci.yml, .github/workflows/release.yml
- update the github action dependencies to the latest v3 (underlying it would use node16 as runtime)
cc @arttor
=> deps: upgrade github action deps

pkg/processor/meta.go
I ran into the issue where I have a deployment that specifcies only `app.kubernetes.io/name` as a label, which results in the creation of an invalid helm template.
Input:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: controller-manager
namespace: system
labels:
app.kubernetes.io/name: operator
spec:
selector:
matchLabels:
app.kubernetes.io/name: operator
replicas: 1
template:
metadata:
labels:
app.kubernetes.io/name: value
annotations:
kubectl.kubernetes.io/default-container: manager
spec:
securityContext:
runAsNonRoot: true
containers:
- command:
- /operator
args:
- operator
- --leader-elect
image: controller:latest
imagePullPolicy: IfNotPresent
name: manager
serviceAccountName: controller-manager
terminationGracePeriodSeconds: 10
```
The resulting bit in the helm template …
=> Support creating a helm template for an object with only helm labels

pkg/helm/init.go
While using the `helmify`, the autogenerated files have executable attributes like `Chart.yaml` and `_helpers.tql`, etc. However, there is no need for these files to execute and the pr can fix it.
=> Update the file's permission

README.md, cmd/helmify/flags.go, examples/app/templates/daemonset.yaml, examples/app/templates/deployment.yaml, examples/app/values.yaml, pkg/config/config.go, pkg/helm/chart.go, pkg/processor/daemonset/daemonset.go, pkg/processor/deployment/deployment.go, pkg/processor/imagePullSecrets/imagePullSecrets.go, pkg/processor/imagePullSecrets/imagePullSecrets_test.go
This is the very minimal implementation. Some notes:
* I can't use a default value for the `imagePullSecrets` in `values.yaml`, as this should only be specified by the user if necessary. To let the user know about the feature, I render a comment in `values.yaml` with an example how to use it.
* I use `toJson` in the helm expression to get started somewhere
* There could be some refactoring done generally to handle `PodSpec` uniformly in one place. Currently there is quite a few duplicate code in `daemonset.go` and `deployment.go`. For this PR I just kept it like it is, and implemented in handling in an own package
* I tested the generate e2e app chart, and it looked good at the first glace.
Please let me know what you think about it.
=> minimal implementation for imagePullSecrets

examples/operator/templates/deployment.yaml, pkg/processor/deployment/deployment.go
we were generating values.yaml with
```
controllerManager:
manager:
env:
key: value
```
but the deployment manifest had:
```
env:
- name: key
value: value: {{ .Values.controllerManager.manager.key }}
```
(it was missing the "env" level...)
so is now fixed by this change
=> fix: env vars with default values in values.yaml

cmd/helmify/flags.go, examples/operator/templates/_helpers.tpl, examples/operator/templates/deployment.yaml, examples/operator/values.yaml, pkg/config/config.go, pkg/helm/init.go, pkg/processor/constraints/constraint.go, pkg/processor/constraints/constraint_test.go, pkg/processor/deployment/deployment.go, test_data/k8s-operator-kustomize.output
this pr adds topology constraints node selector and tolerations templates
=> feat: add constraints

pkg/processor/daemonset/daemonset.go, pkg/processor/deployment/deployment.go
With the new structure for specifying env vars in the template we are experiencing issues. We have a deployment with env var that is either a bool or a number. So normally we specify it as:
```yaml
env:
- name: TEST
value: "1"
```
When that passes through `helmify` we get a template that looks like this:
```yaml
env:
- name: TEST
value: {{ .Values.controllerManager.manager.env.test
}}
```
When the template is parsed, the value "1" gets replace but then the resulting yaml is:
```yaml
env:
- name: TEST
value: 1
```
This is invalid and is rejected by Kubernetes since the env value must always be a string. The same issue would occur if the env value is a boolean.
This PR is an attempt to fix the problem. I already tested that this approach fixes our issue but feel free to adjust it if needed
=> always use quotes for env values

examples/app/templates/daemonset.yaml, examples/app/templates/deployment.yaml, examples/app/values.yaml, examples/operator/templates/deployment.yaml, examples/operator/values.yaml, pkg/processor/deployment/deployment.go, pkg/processor/imagePullSecrets/imagePullSecrets.go, pkg/processor/security-context/container_security_context.go, pkg/processor/security-context/container_security_context_test.go, test_data/k8s-operator-kustomize.output
- adds the (container) security context to the chart generation
=> feat: add support for security context

pkg/processor/security-context/container_security_context.go
The Deployment template generated for the section covering the container 'securityContext' (not the pod 'securityContext') looks like:
```
resources: {{- toYaml .Values.controllerManager.manager.resources
| nindent 10
}}
securityContext: {{- toYaml
.Values.controllerManager.manager.containerSecurityContext
| nindent 8 }}
securityContext:
runAsNonRoot: true
```
As can be seen with the container's 'resources' right above, the appropriate indentation for container values should be '10'.
Otherwise, helm ends up outputting invalid Pod yaml:
```
$ helm template mondoo-operator charts/mondoo-operator -n mondoo-operator --create-namespace --wait | grep -A 6 securityContext
securityContext:
allowPrivilegeEscalation: false
capabilities:
drop:
- ALL
privileged: false
readOnlyRootFilesystem: true …
```
=> further indent container securityContext values

README.md, cmd/helmify/flags.go, pkg/app/context.go, pkg/config/config.go, pkg/helm/chart.go, pkg/helm/init.go, pkg/helmify/model.go, pkg/processor/webhook/cert.go, pkg/processor/webhook/issuer.go
The pr is to add an option `cert-manager-as-subchart` to install the cert-manager as a subchart, it's useful for operator as the cert-manager must be installed before deploying the operator.
=> Add an option cert-manager-as-subchart to install the cert-manager as a subchart

pkg/helm/chart.go, pkg/helm/init.go
The issue I was having is that the key `certManager` in `values.yaml` is not passed to the dependencies. That key should have been `cert-manager` for `installCRDs` to be passed to the dependency. The current code tries to do that, but it ends up being converted to camelCase, so while it correctly enables the dependency, nothing is passed. Since we cannot use camelCase for a dependency alias, I chose to use flatcase.
=> Fix cert manager by using an alias

README.md
There is an indent issue in the demo code, it will cause the make helm command fail when user use it directly.
=> fix: indent issue in the Makefile demo

examples/app/templates/deployment.yaml, examples/app/values.yaml, examples/operator/templates/deployment.yaml, examples/operator/values.yaml, pkg/processor/deployment/deployment.go, pkg/processor/pod/pod.go, pkg/processor/pod/pod_test.go
This change extracts the args from a PodTemplate as values allowing configuring the passed-in parameters.
=> Extract args as values

examples/app/templates/myapp-pdb.yaml, examples/app/values.yaml, pkg/app/app.go, pkg/processor/poddisruptionbudget/pdb.go, pkg/processor/poddisruptionbudget/pdb_test.go, test_data/sample-app.yaml
This allows `helmify` to sensibly handle PodDisruptionBudgets.
=> Add PodDisruptionBudget processor

pkg/processor/pod/pod.go, pkg/processor/pod/pod_test.go
Previously, we were splitting image addresses at the _last_ instance of a colon; this had unfortunate side-effects when said address included a digest.
This change causes us to look for the _first_ instance of a colon, allowing both tag and digest to properly co-exist; we don't try to do anything fancier than that.
=> Handle images with digests

pkg/processor/service/service.go
This issue ultimately presents as
```
ports:
- port: 8000
protocol: TCP
targetPort:8000---
apiVersion: policy/v1
kind PodDisruptionBudget
metadata:
```
=> fix: don't strip newlines after the templated value

README.md, cmd/helmify/flags.go, pkg/config/config.go, pkg/metadata/metadata.go
As titled. Enhancement for https://github.com/arttor/helmify/issues/138.
@arttor Could you please have a review?
=> Add original-name flags for remaining original resource name

README.md, cmd/helmify/flags.go, pkg/config/config.go, pkg/processor/meta.go
Updated the repo to include the namespace in the metadata of the helm chart generated.
This is to overcome the enhancement requested in this [issue](https://github.com/arttor/helmify/issues/143).
Tested by running the test mentioned in the readme documentation.
=> Add Namespace to the metadata of generated resources in the Helm Chart.

examples/app/templates/deployment.yaml, examples/app/values.yaml, examples/operator/templates/deployment.yaml, examples/operator/values.yaml, pkg/processor/pod/pod.go, pkg/processor/pod/pod_test.go, test_data/sample-app.yaml
Hi! I have created this PR to check if addition of templating for  Pod-level SecurityContext could be accepted.
I find this useful as, depending on who is using your helm Chart, they may need to define a more or less strict securityContext depending on their security policies.
Closes #149
=> add support for pod level securityContext

examples/app/templates/myapp-service.yaml, examples/app/templates/nginx.yaml, examples/operator/templates/metrics-service.yaml, examples/operator/templates/webhook-service.yaml, pkg/processor/service/service.go
A wild tab appeared in my code.
=> fix wild tab in service

README.md, cmd/helmify/flags.go, pkg/config/config.go, pkg/processor/deployment/deployment.go, pkg/processor/service/service.go, pkg/processor/webhook/cert.go, pkg/processor/webhook/issuer.go, pkg/processor/webhook/mutating.go, pkg/processor/webhook/validating.go
=> Add an option for enable/disable webhook for a standard operator generated by kubebuilder

examples/operator/templates/deployment.yaml, examples/operator/values.yaml, pkg/processor/deployment/deployment.go, pkg/processor/deployment/deployment_test.go, test_data/k8s-operator-kustomize.output
Issue: https://github.com/arttor/helmify/issues/157
=> add support for deployment strategy attribute
